version: "2"

services:

  webui:
    build: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  database:
    image: sql
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
